### ISSUE TITLE
http2 tracing is broken on windows

### ISSUE THREAD

**Issue by aitva** [davecheney/httpstat#90] opened 2016-09-28 09:39 UTC
I'm testing httpstat on a Windows machine and I get a huge TCP Connection time.

```
D:\>httpstat http://139.110.74.200/dsrv/status

Connected to 139.110.74.200:80

HTTP/1.1 200 OK
Server: Apache/2.4.6 (Red Hat Enterprise Linux) PHP/5.4.16
Content-Type: text/xml
Date: Thu, 11 Aug 2016 09:36:27 GMT
X-Powered-By: PHP/5.4.16

Body discarded

   DNS Lookup   TCP Connection   Server Processing   Content Transfer
[       0ms  |     9223372036854ms  |              9ms  |             1ms  ]
             |                |                   |                  |
    namelookup:0ms            |                   |                  |
                        connect:9223372036854ms         |                  |
                                      starttransfer:9223372036854ms        |
                                                                 total:922337203
6854ms
```

I have tried changing the `HTTP_PROXY` variable and when using a local `cntlm` proxy it goes back to something reasonable:

```
D:\>set HTTP_PROXY=localhost:3128

D:\>set HTTPS_PROXY=localhost:3128

D:\>httpstat http://139.110.74.200/dsrv/status

Connected to 127.0.0.1:3128

HTTP/1.1 200 OK
Server: Apache/2.4.6 (Red Hat Enterprise Linux) PHP/5.4.16
Accept-Ranges: none
Content-Length: 415
Content-Type: text/xml
Date: Thu, 11 Aug 2016 09:43:50 GMT
Proxy-Connection: close
Via: 1.1 gproxy.postal.local:8080
X-Powered-By: PHP/5.4.16

Body discarded

   DNS Lookup   TCP Connection   Server Processing   Content Transfer
[       0ms  |           0ms  |             29ms  |             0ms  ]
             |                |                   |                  |
    namelookup:0ms            |                   |                  |
                        connect:0ms               |                  |
                                      starttransfer:29ms             |
                                                                 total:29ms
```

I can provide additional information if needed.

(Thanks for this tool, it is awesome !)

**Comment by davecheney** [comment] 2016-09-29 02:18
@aitva how reproducible is this?

**Comment by moorereason** [comment] 2016-09-29 03:18
I can reproduce it on Windows 10 but only when making HTTP/2 requests.  `t3` (WroteRequest) and `t4` (GotFirstResponseByte) are coming back with zero time values.  The request appears to be completing, but the `httptrace` hooks don't appear to be firing.

HTTP/1.1 requests (http and https) work fine for me, which is different from what @aitva is reporting.

**Comment by moorereason** [comment] 2016-09-29 04:42
We've likely found a bug in Go 1.7.1 windows/amd64.

On an HTTP/2 trace, I only see the following hooks firing (in this order):

```text
$ go run main.go https://www.google.com/
GetConn
DNSStart
DNSDone
ConnectStart
ConnectDone
```

On a working, non-HTTP/2 trace, I get hooks firing in this order:

```text
$ go run main.go http://www.google.com/
GetConn
DNSStart
DNSDone
ConnectStart
ConnectDone
GotConn
WroteHeaders
WroteRequest
GotFirstResponseByte
PutIdleConn
```

I've created a [test branch](https://github.com/moorereason/httpstat/tree/iss90) that prints out when each httptrace hook if anyone wants to test it.  

/cc @bradfitz @rakyll

PS - Dave, can you update the title of this issue?  "http2 tracing is broken on windows"

**Comment by h1k0n** [comment] 2016-09-29 05:00
I know how th reproduce it. If we directly set proxy server's ip in
export http_proxy=${ip}:${port}
httpstat https://www.google.com
or directly set server's ip like this:
httpstat http://${ip}:${port}
then this issue happen.
The reason is DNSStart and DNSDone is not triggered.

**Comment by h1k0n** [comment] 2016-09-29 05:04
I know how to reproduce it. If we directly set proxy server's ip in
export http_proxy=${ip}:${port}
httpstat https://www.google.com
or directly set server's ip like this:
httpstat http://${ip}:${port}
then this issue happen.
The reason is DNSStart and DNSDone is not triggered.

**Comment by moorereason** [comment] 2016-09-29 05:37
@h1k0n, thanks for the heads up, but that's a separate issue.  See #97

**Comment by moorereason** [comment] 2016-09-29 14:33
Works correctly on Windows 7.

**Comment by moorereason** [comment] 2016-09-29 14:55
@h1k0n was right about the original report being about skipping DNS, which means I hijacked this ticket.  My apologies.  The original report should be resolved along with #97.

Now, back to Windows...

I tested on a standard Windows 10 machine (version 1511, build 10586.589) this morning, and it works fine.  Last night I was testing on Windows 10 Insider edition, but I don't have that device with me right now.  I'll try to do more testing this evening (that's about 8 hours from now).

**Comment by aitva** [comment] 2016-09-29 16:17
I am having this issue on Windows 7. I have tried with a different server and I get the same result :

```
D:\>httpstat http://159.217.43.49

Connected to 159.217.43.49:80

HTTP/1.1 200 OK
Server: Apache/2.2.11 (Win32) PHP/5.3.0
Content-Length: 4959
Content-Type: text/html
Date: Thu, 29 Sep 2016 15:42:17 GMT
X-Powered-By: PHP/5.3.0

Body discarded

   DNS Lookup   TCP Connection   Server Processing   Content Transfer
[       0ms  |     9223372036854ms  |             11ms  |             0ms  ]
             |                |                   |                  |
    namelookup:0ms            |                   |                  |
                        connect:9223372036854ms         |                  |
                                      starttransfer:9223372036854ms        |
                                                                 total:922337203
6854ms
```

But, when doing the same request with the hostname the issue goes away :

```
D:\>httpstat http://srv-dbovs

Connected to 159.217.43.49:80

HTTP/1.1 200 OK
Server: Apache/2.2.11 (Win32) PHP/5.3.0
Content-Length: 4959
Content-Type: text/html
Date: Thu, 29 Sep 2016 15:42:22 GMT
X-Powered-By: PHP/5.3.0

Body discarded

   DNS Lookup   TCP Connection   Server Processing   Content Transfer
[       5ms  |           5ms  |             10ms  |             0ms  ]
             |                |                   |                  |
    namelookup:5ms            |                   |                  |
                        connect:10ms              |                  |
                                      starttransfer:20ms             |
                                                                 total:21ms
```

I have also tried on a Debian 8 computer and I can't reproduce the problem.

The issue seems to arise on Windows 7 and only without DNS lookup. 
I can provide you more information, but I will need guidance. There might be something in the corporate network or in my configuration which causes the issue.

**Comment by moorereason** [comment] 2016-09-29 16:53
@aitva, The issue you're seeing should have been fixed already.

What version of httpstat are you running (`httpstat -v`)?  If you're building manually, what git commit are you using (`git log --oneline -1`).

**Comment by moorereason** [comment] 2016-09-29 23:10
Confirming that I'm seeing this issue on Windows 10 Pro Insider Preview Build 14379.rs1_release.160627-1607.  I'm not sure what this Insider build could be doing to break the network stack, so we may can just close this as, or at least remove it from the Stable release milestone. 

This Insider build is about to expire anyway, so I'll need to install the newest build and test after the upgrade.

**Comment by davecheney** [comment] 2016-09-29 23:18
@aitva can you please use the 1.0.0-beta.1 release binary that I made last
night. If it fails please include the output of httpstat -v with your
report.

**Comment by aitva** [comment] 2016-09-30 15:06
I have just tried the binary release, everything is working.
@moorereason @davecheney thank you for the correction!

**Comment by moorereason** [comment] 2016-09-30 16:17
@davecheney,
I installed the latest Windows 10 Pro Insider Preview last night, and it bricked my laptop.   :trophy: 

Please close this issue.  The stable Windows 10 builds appear to be working just fine.

**Closed** 2016-09-30 23:24 UTC
Labels: bug, help wanted
