### ISSUE TITLE
Can't connect to host if it can't work with HTTPS

### ISSUE THREAD

**Issue by bogem** [davecheney/httpstat#92] opened 2016-09-28 11:59 UTC
I can't connect to host, if it works only with HTTP, without obvious declaration of protocol:
![2016-09-28 13 55 46](https://cloud.githubusercontent.com/assets/13235519/18912583/715218ce-8583-11e6-92ff-abb35ca8b8c1.png)

**Comment by davecheney** [comment] 2016-09-28 12:02
This is a deliberate choice to default to https if no scheme is provided. 

What error message would you like to see I this case?

**Comment by bogem** [comment] 2016-09-28 12:05
I think, in this case it would be perfect, if httpstat would check the support of HTTPS protocol on site. So if httpstat could't connect to site with HTTPS, it would connect to it with HTTP.

**Comment by davecheney** [comment] 2016-09-28 12:12
Sorry, that's beyond the remit of this tool. I think we're already doing more than we should by trying to guess the scheme if one is not provided.

**Comment by bogem** [comment] 2016-09-28 12:16
Then error message could be like "Can't connect to host with HTTPS. Please provide a scheme to URL"

**Comment by davecheney** [comment] 2016-09-28 12:31
If we're going to do that, then I'd prefer to drop the automatic scheme prefix and just say "not a url, try again".

**Comment by bogem** [comment] 2016-09-28 12:53
Yeah, it's a good idea too

**Comment by moorereason** [comment] 2016-09-28 15:23
What if we output "**Connecting to ...**" prior to dialing?  Example:

```text
$ httpstat dave.cheney.net
Connecting to https://dave.cheney.net

2016/09/28 10:19:46 unable to connect to host 128.199.248.140:443 dial tcp 128.199.248.140:443: getsockopt: connection refused
exit status 1
```

Normal operation:

```text
$ httpstat http://dave.cheney.net
Connecting to http://dave.cheney.net

Connected to 128.199.248.140:80

HTTP/1.1 200 OK
Server: nginx/1.2.1
Content-Type: text/html; charset=UTF-8
Date: Wed, 28 Sep 2016 15:21:04 GMT
Link: <http://dave.cheney.net/wp-json/>; rel="https://api.w.org/"
X-Powered-By: PHP/5.4.45-0+deb7u2
Connection: keep-alive

Body discarded

   DNS Lookup   TCP Connection   Server Processing   Content Transfer
[      44ms  |         228ms  |            539ms  |           455ms  ]
             |                |                   |                  |
    namelookup:44ms           |                   |                  |
                        connect:273ms             |                  |
                                      starttransfer:813ms            |
                                                                 total:1268ms
```

**Comment by davecheney** [comment] 2016-09-28 20:15
I'm not down with more output, the next thing people will ask for is a flag
to turn these two lines off.

**Comment by davecheney** [comment] 2016-09-28 22:42
I'm going to close this issue as working as intended. The result is surprising, but intended due to the deliberate decision to prefer https over http when no scheme is provided by the user.

**Closed by davecheney** 2016-09-28 22:42 UTC
Labels: bug
